version: 2
updates:
  - package-ecosystem: composer
    directory: /src/api  # nebo kde máš composer.json
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - php
