---
name: Obecné
about: Prostor pro všeobecné diskuze o projektu.
title: '[Obecné] '
labels: discussion
---

## O čem chcete diskutovat?

Napište sem svůj příspěvek, otázku nebo komentář k projektu.

## Další informace

Můžete přidat jakékoli další podrobnosti nebo kontext.

---

**Děkujeme za vaši účast na diskuzi!**
