---
name: Otázka
about: Položte otázku a požádejte komunitu o pomoc.
title: '[Otázka] '
labels: question
---

## Popis otázky

Napište prosím jasně a srozumitelně, s čím potřebujete pomoct.

## Kroky, jak problém vyvolat

1.  
2.  
3.  

## Co jste už zkusili

-  
-  

## Další informace

(Přidejte jakékoliv další informace, které by mohly být užitečné.)
