---
name: "Předveďte a řekněte"
about: "Pochlubte se něčím, co jste vytvořili, a sdílejte to s komunitou."
title: '[Ukázka] '
labels: showcase
---

## Popis projektu / věci, kterou chcete ukázat

Napište něco o svém projektu nebo co jste vytvořili.

## Co to dělá

Popište funkce nebo vlastnosti.

## Odkazy

- Demo:  
- Kód:  
- Další info:  

## Další poznámky

(Přidejte cokoli dalšího, co chcete sdílet.)
