name: 游댢 Refaktoring
description: Zlep코en칤 struktury nebo kvality k칩du bez zm캩ny jeho chov치n칤
title: "[Refaktoring] "
labels: ["stav:k-posouzeni"]
body:
  - type: markdown
    attributes:
      value: |
        游녤 **D콢le쬴t칠:** Za캜ni n치zev issue prefixem s oblast칤 v hranat칳ch z치vork치ch.  
        Nap콏칤klad: `[Web] Mo쬹ost duplikace receptu` nebo `[Admin] Nov칳 layout detailu`.

        Dostupn칠 oblasti: `Web`, `Admin`, `Api`

  - type: textarea
    id: scope
    attributes:
      label: Co je pot콏eba refaktorovat?
      placeholder: "Kter치 캜치st k칩du a pro캜?"
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Pro캜 je to pot콏eba?
      placeholder: "Lep코칤 캜itelnost, v칳kon, testovatelnost..."
