/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as PrivateRouteImport } from './app/routes/_private'
import { Route as PublicIndexRouteImport } from './app/routes/_public/index'
import { Route as VerifyEmailOvereniEmailuIndexRouteImport } from './app/routes/_verifyEmail/overeni-emailu/index'
import { Route as VerifyEmailOvereniEmailuZadostIndexRouteImport } from './app/routes/_verifyEmail/overeni-emailu-zadost/index'
import { Route as VerifyEmailOvereniEmailuZadostUspechIndexRouteImport } from './app/routes/_verifyEmail/overeni-emailu-zadost-uspech/index'
import { Route as VerifyEmailOvereniEmailuUspechIndexRouteImport } from './app/routes/_verifyEmail/overeni-emailu-uspech/index'
import { Route as PublicVlastnostiIndexRouteImport } from './app/routes/_public/vlastnosti/index'
import { Route as PublicCenikIndexRouteImport } from './app/routes/_public/cenik/index'
import { Route as PrivateTestIndexRouteImport } from './app/routes/_private/test/index'
import { Route as PasswordResetZapomenuteHesloIndexRouteImport } from './app/routes/_passwordReset/zapomenute-heslo/index'
import { Route as PasswordResetZapomenuteHesloUspechIndexRouteImport } from './app/routes/_passwordReset/zapomenute-heslo-uspech/index'
import { Route as PasswordResetObnovaHeslaIndexRouteImport } from './app/routes/_passwordReset/obnova-hesla/index'
import { Route as PasswordResetObnovaHeslaUspechIndexRouteImport } from './app/routes/_passwordReset/obnova-hesla-uspech/index'
import { Route as AuthRegistraceIndexRouteImport } from './app/routes/_auth/registrace/index'
import { Route as AuthRegistraceUspechIndexRouteImport } from './app/routes/_auth/registrace-uspech/index'
import { Route as AuthPrihlaseniIndexRouteImport } from './app/routes/_auth/prihlaseni/index'
import { Route as VerifyEmailOvereniEmailuTokenRouteImport } from './app/routes/_verifyEmail/overeni-emailu/$token'
import { Route as PasswordResetObnovaHeslaTokenRouteImport } from './app/routes/_passwordReset/obnova-hesla/$token'

const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/_public/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailOvereniEmailuIndexRoute =
  VerifyEmailOvereniEmailuIndexRouteImport.update({
    id: '/_verifyEmail/overeni-emailu/',
    path: '/overeni-emailu/',
    getParentRoute: () => rootRouteImport,
  } as any)
const VerifyEmailOvereniEmailuZadostIndexRoute =
  VerifyEmailOvereniEmailuZadostIndexRouteImport.update({
    id: '/_verifyEmail/overeni-emailu-zadost/',
    path: '/overeni-emailu-zadost/',
    getParentRoute: () => rootRouteImport,
  } as any)
const VerifyEmailOvereniEmailuZadostUspechIndexRoute =
  VerifyEmailOvereniEmailuZadostUspechIndexRouteImport.update({
    id: '/_verifyEmail/overeni-emailu-zadost-uspech/',
    path: '/overeni-emailu-zadost-uspech/',
    getParentRoute: () => rootRouteImport,
  } as any)
const VerifyEmailOvereniEmailuUspechIndexRoute =
  VerifyEmailOvereniEmailuUspechIndexRouteImport.update({
    id: '/_verifyEmail/overeni-emailu-uspech/',
    path: '/overeni-emailu-uspech/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublicVlastnostiIndexRoute = PublicVlastnostiIndexRouteImport.update({
  id: '/_public/vlastnosti/',
  path: '/vlastnosti/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicCenikIndexRoute = PublicCenikIndexRouteImport.update({
  id: '/_public/cenik/',
  path: '/cenik/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateTestIndexRoute = PrivateTestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => PrivateRoute,
} as any)
const PasswordResetZapomenuteHesloIndexRoute =
  PasswordResetZapomenuteHesloIndexRouteImport.update({
    id: '/_passwordReset/zapomenute-heslo/',
    path: '/zapomenute-heslo/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PasswordResetZapomenuteHesloUspechIndexRoute =
  PasswordResetZapomenuteHesloUspechIndexRouteImport.update({
    id: '/_passwordReset/zapomenute-heslo-uspech/',
    path: '/zapomenute-heslo-uspech/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PasswordResetObnovaHeslaIndexRoute =
  PasswordResetObnovaHeslaIndexRouteImport.update({
    id: '/_passwordReset/obnova-hesla/',
    path: '/obnova-hesla/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PasswordResetObnovaHeslaUspechIndexRoute =
  PasswordResetObnovaHeslaUspechIndexRouteImport.update({
    id: '/_passwordReset/obnova-hesla-uspech/',
    path: '/obnova-hesla-uspech/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthRegistraceIndexRoute = AuthRegistraceIndexRouteImport.update({
  id: '/_auth/registrace/',
  path: '/registrace/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegistraceUspechIndexRoute =
  AuthRegistraceUspechIndexRouteImport.update({
    id: '/_auth/registrace-uspech/',
    path: '/registrace-uspech/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthPrihlaseniIndexRoute = AuthPrihlaseniIndexRouteImport.update({
  id: '/_auth/prihlaseni/',
  path: '/prihlaseni/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailOvereniEmailuTokenRoute =
  VerifyEmailOvereniEmailuTokenRouteImport.update({
    id: '/_verifyEmail/overeni-emailu/$token',
    path: '/overeni-emailu/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const PasswordResetObnovaHeslaTokenRoute =
  PasswordResetObnovaHeslaTokenRouteImport.update({
    id: '/_passwordReset/obnova-hesla/$token',
    path: '/obnova-hesla/$token',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/obnova-hesla/$token': typeof PasswordResetObnovaHeslaTokenRoute
  '/overeni-emailu/$token': typeof VerifyEmailOvereniEmailuTokenRoute
  '/prihlaseni/': typeof AuthPrihlaseniIndexRoute
  '/registrace-uspech/': typeof AuthRegistraceUspechIndexRoute
  '/registrace/': typeof AuthRegistraceIndexRoute
  '/obnova-hesla-uspech/': typeof PasswordResetObnovaHeslaUspechIndexRoute
  '/obnova-hesla/': typeof PasswordResetObnovaHeslaIndexRoute
  '/zapomenute-heslo-uspech/': typeof PasswordResetZapomenuteHesloUspechIndexRoute
  '/zapomenute-heslo/': typeof PasswordResetZapomenuteHesloIndexRoute
  '/test/': typeof PrivateTestIndexRoute
  '/cenik/': typeof PublicCenikIndexRoute
  '/vlastnosti/': typeof PublicVlastnostiIndexRoute
  '/overeni-emailu-uspech/': typeof VerifyEmailOvereniEmailuUspechIndexRoute
  '/overeni-emailu-zadost-uspech/': typeof VerifyEmailOvereniEmailuZadostUspechIndexRoute
  '/overeni-emailu-zadost/': typeof VerifyEmailOvereniEmailuZadostIndexRoute
  '/overeni-emailu/': typeof VerifyEmailOvereniEmailuIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/obnova-hesla/$token': typeof PasswordResetObnovaHeslaTokenRoute
  '/overeni-emailu/$token': typeof VerifyEmailOvereniEmailuTokenRoute
  '/prihlaseni': typeof AuthPrihlaseniIndexRoute
  '/registrace-uspech': typeof AuthRegistraceUspechIndexRoute
  '/registrace': typeof AuthRegistraceIndexRoute
  '/obnova-hesla-uspech': typeof PasswordResetObnovaHeslaUspechIndexRoute
  '/obnova-hesla': typeof PasswordResetObnovaHeslaIndexRoute
  '/zapomenute-heslo-uspech': typeof PasswordResetZapomenuteHesloUspechIndexRoute
  '/zapomenute-heslo': typeof PasswordResetZapomenuteHesloIndexRoute
  '/test': typeof PrivateTestIndexRoute
  '/cenik': typeof PublicCenikIndexRoute
  '/vlastnosti': typeof PublicVlastnostiIndexRoute
  '/overeni-emailu-uspech': typeof VerifyEmailOvereniEmailuUspechIndexRoute
  '/overeni-emailu-zadost-uspech': typeof VerifyEmailOvereniEmailuZadostUspechIndexRoute
  '/overeni-emailu-zadost': typeof VerifyEmailOvereniEmailuZadostIndexRoute
  '/overeni-emailu': typeof VerifyEmailOvereniEmailuIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/_passwordReset/obnova-hesla/$token': typeof PasswordResetObnovaHeslaTokenRoute
  '/_verifyEmail/overeni-emailu/$token': typeof VerifyEmailOvereniEmailuTokenRoute
  '/_auth/prihlaseni/': typeof AuthPrihlaseniIndexRoute
  '/_auth/registrace-uspech/': typeof AuthRegistraceUspechIndexRoute
  '/_auth/registrace/': typeof AuthRegistraceIndexRoute
  '/_passwordReset/obnova-hesla-uspech/': typeof PasswordResetObnovaHeslaUspechIndexRoute
  '/_passwordReset/obnova-hesla/': typeof PasswordResetObnovaHeslaIndexRoute
  '/_passwordReset/zapomenute-heslo-uspech/': typeof PasswordResetZapomenuteHesloUspechIndexRoute
  '/_passwordReset/zapomenute-heslo/': typeof PasswordResetZapomenuteHesloIndexRoute
  '/_private/test/': typeof PrivateTestIndexRoute
  '/_public/cenik/': typeof PublicCenikIndexRoute
  '/_public/vlastnosti/': typeof PublicVlastnostiIndexRoute
  '/_verifyEmail/overeni-emailu-uspech/': typeof VerifyEmailOvereniEmailuUspechIndexRoute
  '/_verifyEmail/overeni-emailu-zadost-uspech/': typeof VerifyEmailOvereniEmailuZadostUspechIndexRoute
  '/_verifyEmail/overeni-emailu-zadost/': typeof VerifyEmailOvereniEmailuZadostIndexRoute
  '/_verifyEmail/overeni-emailu/': typeof VerifyEmailOvereniEmailuIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/obnova-hesla/$token'
    | '/overeni-emailu/$token'
    | '/prihlaseni/'
    | '/registrace-uspech/'
    | '/registrace/'
    | '/obnova-hesla-uspech/'
    | '/obnova-hesla/'
    | '/zapomenute-heslo-uspech/'
    | '/zapomenute-heslo/'
    | '/test/'
    | '/cenik/'
    | '/vlastnosti/'
    | '/overeni-emailu-uspech/'
    | '/overeni-emailu-zadost-uspech/'
    | '/overeni-emailu-zadost/'
    | '/overeni-emailu/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/obnova-hesla/$token'
    | '/overeni-emailu/$token'
    | '/prihlaseni'
    | '/registrace-uspech'
    | '/registrace'
    | '/obnova-hesla-uspech'
    | '/obnova-hesla'
    | '/zapomenute-heslo-uspech'
    | '/zapomenute-heslo'
    | '/test'
    | '/cenik'
    | '/vlastnosti'
    | '/overeni-emailu-uspech'
    | '/overeni-emailu-zadost-uspech'
    | '/overeni-emailu-zadost'
    | '/overeni-emailu'
  id:
    | '__root__'
    | '/_private'
    | '/_public/'
    | '/_passwordReset/obnova-hesla/$token'
    | '/_verifyEmail/overeni-emailu/$token'
    | '/_auth/prihlaseni/'
    | '/_auth/registrace-uspech/'
    | '/_auth/registrace/'
    | '/_passwordReset/obnova-hesla-uspech/'
    | '/_passwordReset/obnova-hesla/'
    | '/_passwordReset/zapomenute-heslo-uspech/'
    | '/_passwordReset/zapomenute-heslo/'
    | '/_private/test/'
    | '/_public/cenik/'
    | '/_public/vlastnosti/'
    | '/_verifyEmail/overeni-emailu-uspech/'
    | '/_verifyEmail/overeni-emailu-zadost-uspech/'
    | '/_verifyEmail/overeni-emailu-zadost/'
    | '/_verifyEmail/overeni-emailu/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRoute: typeof PrivateRouteWithChildren
  PublicIndexRoute: typeof PublicIndexRoute
  PasswordResetObnovaHeslaTokenRoute: typeof PasswordResetObnovaHeslaTokenRoute
  VerifyEmailOvereniEmailuTokenRoute: typeof VerifyEmailOvereniEmailuTokenRoute
  AuthPrihlaseniIndexRoute: typeof AuthPrihlaseniIndexRoute
  AuthRegistraceUspechIndexRoute: typeof AuthRegistraceUspechIndexRoute
  AuthRegistraceIndexRoute: typeof AuthRegistraceIndexRoute
  PasswordResetObnovaHeslaUspechIndexRoute: typeof PasswordResetObnovaHeslaUspechIndexRoute
  PasswordResetObnovaHeslaIndexRoute: typeof PasswordResetObnovaHeslaIndexRoute
  PasswordResetZapomenuteHesloUspechIndexRoute: typeof PasswordResetZapomenuteHesloUspechIndexRoute
  PasswordResetZapomenuteHesloIndexRoute: typeof PasswordResetZapomenuteHesloIndexRoute
  PublicCenikIndexRoute: typeof PublicCenikIndexRoute
  PublicVlastnostiIndexRoute: typeof PublicVlastnostiIndexRoute
  VerifyEmailOvereniEmailuUspechIndexRoute: typeof VerifyEmailOvereniEmailuUspechIndexRoute
  VerifyEmailOvereniEmailuZadostUspechIndexRoute: typeof VerifyEmailOvereniEmailuZadostUspechIndexRoute
  VerifyEmailOvereniEmailuZadostIndexRoute: typeof VerifyEmailOvereniEmailuZadostIndexRoute
  VerifyEmailOvereniEmailuIndexRoute: typeof VerifyEmailOvereniEmailuIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_verifyEmail/overeni-emailu/': {
      id: '/_verifyEmail/overeni-emailu/'
      path: '/overeni-emailu'
      fullPath: '/overeni-emailu/'
      preLoaderRoute: typeof VerifyEmailOvereniEmailuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_verifyEmail/overeni-emailu-zadost/': {
      id: '/_verifyEmail/overeni-emailu-zadost/'
      path: '/overeni-emailu-zadost'
      fullPath: '/overeni-emailu-zadost/'
      preLoaderRoute: typeof VerifyEmailOvereniEmailuZadostIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_verifyEmail/overeni-emailu-zadost-uspech/': {
      id: '/_verifyEmail/overeni-emailu-zadost-uspech/'
      path: '/overeni-emailu-zadost-uspech'
      fullPath: '/overeni-emailu-zadost-uspech/'
      preLoaderRoute: typeof VerifyEmailOvereniEmailuZadostUspechIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_verifyEmail/overeni-emailu-uspech/': {
      id: '/_verifyEmail/overeni-emailu-uspech/'
      path: '/overeni-emailu-uspech'
      fullPath: '/overeni-emailu-uspech/'
      preLoaderRoute: typeof VerifyEmailOvereniEmailuUspechIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/vlastnosti/': {
      id: '/_public/vlastnosti/'
      path: '/vlastnosti'
      fullPath: '/vlastnosti/'
      preLoaderRoute: typeof PublicVlastnostiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/cenik/': {
      id: '/_public/cenik/'
      path: '/cenik'
      fullPath: '/cenik/'
      preLoaderRoute: typeof PublicCenikIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/test/': {
      id: '/_private/test/'
      path: '/test'
      fullPath: '/test/'
      preLoaderRoute: typeof PrivateTestIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_passwordReset/zapomenute-heslo/': {
      id: '/_passwordReset/zapomenute-heslo/'
      path: '/zapomenute-heslo'
      fullPath: '/zapomenute-heslo/'
      preLoaderRoute: typeof PasswordResetZapomenuteHesloIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_passwordReset/zapomenute-heslo-uspech/': {
      id: '/_passwordReset/zapomenute-heslo-uspech/'
      path: '/zapomenute-heslo-uspech'
      fullPath: '/zapomenute-heslo-uspech/'
      preLoaderRoute: typeof PasswordResetZapomenuteHesloUspechIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_passwordReset/obnova-hesla/': {
      id: '/_passwordReset/obnova-hesla/'
      path: '/obnova-hesla'
      fullPath: '/obnova-hesla/'
      preLoaderRoute: typeof PasswordResetObnovaHeslaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_passwordReset/obnova-hesla-uspech/': {
      id: '/_passwordReset/obnova-hesla-uspech/'
      path: '/obnova-hesla-uspech'
      fullPath: '/obnova-hesla-uspech/'
      preLoaderRoute: typeof PasswordResetObnovaHeslaUspechIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/registrace/': {
      id: '/_auth/registrace/'
      path: '/registrace'
      fullPath: '/registrace/'
      preLoaderRoute: typeof AuthRegistraceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/registrace-uspech/': {
      id: '/_auth/registrace-uspech/'
      path: '/registrace-uspech'
      fullPath: '/registrace-uspech/'
      preLoaderRoute: typeof AuthRegistraceUspechIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/prihlaseni/': {
      id: '/_auth/prihlaseni/'
      path: '/prihlaseni'
      fullPath: '/prihlaseni/'
      preLoaderRoute: typeof AuthPrihlaseniIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_verifyEmail/overeni-emailu/$token': {
      id: '/_verifyEmail/overeni-emailu/$token'
      path: '/overeni-emailu/$token'
      fullPath: '/overeni-emailu/$token'
      preLoaderRoute: typeof VerifyEmailOvereniEmailuTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_passwordReset/obnova-hesla/$token': {
      id: '/_passwordReset/obnova-hesla/$token'
      path: '/obnova-hesla/$token'
      fullPath: '/obnova-hesla/$token'
      preLoaderRoute: typeof PasswordResetObnovaHeslaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PrivateRouteChildren {
  PrivateTestIndexRoute: typeof PrivateTestIndexRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateTestIndexRoute: PrivateTestIndexRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PrivateRoute: PrivateRouteWithChildren,
  PublicIndexRoute: PublicIndexRoute,
  PasswordResetObnovaHeslaTokenRoute: PasswordResetObnovaHeslaTokenRoute,
  VerifyEmailOvereniEmailuTokenRoute: VerifyEmailOvereniEmailuTokenRoute,
  AuthPrihlaseniIndexRoute: AuthPrihlaseniIndexRoute,
  AuthRegistraceUspechIndexRoute: AuthRegistraceUspechIndexRoute,
  AuthRegistraceIndexRoute: AuthRegistraceIndexRoute,
  PasswordResetObnovaHeslaUspechIndexRoute:
    PasswordResetObnovaHeslaUspechIndexRoute,
  PasswordResetObnovaHeslaIndexRoute: PasswordResetObnovaHeslaIndexRoute,
  PasswordResetZapomenuteHesloUspechIndexRoute:
    PasswordResetZapomenuteHesloUspechIndexRoute,
  PasswordResetZapomenuteHesloIndexRoute:
    PasswordResetZapomenuteHesloIndexRoute,
  PublicCenikIndexRoute: PublicCenikIndexRoute,
  PublicVlastnostiIndexRoute: PublicVlastnostiIndexRoute,
  VerifyEmailOvereniEmailuUspechIndexRoute:
    VerifyEmailOvereniEmailuUspechIndexRoute,
  VerifyEmailOvereniEmailuZadostUspechIndexRoute:
    VerifyEmailOvereniEmailuZadostUspechIndexRoute,
  VerifyEmailOvereniEmailuZadostIndexRoute:
    VerifyEmailOvereniEmailuZadostIndexRoute,
  VerifyEmailOvereniEmailuIndexRoute: VerifyEmailOvereniEmailuIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
