packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  esbuild: true

catalog:
  "@heroui/react": "3.0.3"
  "@heroui/styles": "3.0.3"
  "@reduxjs/toolkit": "^2.11.2"
  "@tanstack/react-router": "^1.169.1"
  "@tanstack/router-plugin": "^1.167.32"
  "@types/node": "^25.6.0"
  "@types/react": "^19.2.14"
  "@types/react-dom": "^19.2.3"
  eslint: "^10.3.0"
  react: "^19.2.5"
  react-dom: "^19.2.5"
  react-redux: "^9.2.0"
  tailwindcss: "^4.2.4"
  typescript: "~6.0.3"
  typescript-eslint: "^8.59.1"
  vite: "^8.0.10"
